### ISSUE TITLE
alt+click conflicts with multiple line selection using mouse on Mac

### ISSUE THREAD

**Issue by nunosans** [alvesjtiago/click-to-partial#3]
I'm using Sublime Text 3 (Build 3126) on macOS 10.12.1. I experience an issue where after installing this plugin I can no longer select multiple lines using the mouse.

Steps to reproduce:
- Open any file containing text
- Hold alt and select a block of text

Expected behaviour:
- I expect to see a selection block with multiple input cursors, one on each line. As you can see on the GIF below.

![multiple-selection-by-cursos-macos](https://cloud.githubusercontent.com/assets/546823/21292208/f0520fb6-c53f-11e6-813d-d65fb142583e.gif)

Issue:
- With this plugin installed, I can no longer select multiple lines. The text selection doesn't happen and Sublime doesn't respond to the selection.

**Comment by alvesjtiago** [comment]
@nunosans thanks for reporting this. After analysing and comparing with #2, I believe it's better to match with` ["super", "shift"]` therefore making the call with cmd+shift+click. Only cmd+click (`["cmd"]`) removes multi-selection in ST3. Will make the necessary changes, merge and close the pull request.
Thanks again for reporting. Let me know if you have any issues after the changes.

**Comment by nunosans** [comment]
@alvesjtiago ack. thanks
